Repository SSUMC-6th/Android_A, pull requests merged in 2024-06, with the labels that each got.

#36 [kara/#33] feat : 7주차 구현
  UMC_6th/app/build.gradle.kts
  UMC_6th/app/src/main/AndroidManifest.xml
  UMC_6th/app/src/main/java/com/example/myfirstapp/Album.kt
  UMC_6th/app/src/main/java/com/example/myfirstapp/AlbumDao.kt
  UMC_6th/app/src/main/java/com/example/myfirstapp/AlbumFragment.kt
  UMC_6th/app/src/main/java/com/example/myfirstapp/AlbumRVAdapter.kt
  UMC_6th/app/src/main/java/com/example/myfirstapp/Constant.kt
  UMC_6th/app/src/main/java/com/example/myfirstapp/CustomSnackbar.kt
  UMC_6th/app/src/main/java/com/example/myfirstapp/HomeFragment.kt
  UMC_6th/app/src/main/java/com/example/myfirstapp/LockerAlbumRVAdapter.kt
  UMC_6th/app/src/main/java/com/example/myfirstapp/MainActivity.kt
  UMC_6th/app/src/main/java/com/example/myfirstapp/SavedSongFragment.kt
  UMC_6th/app/src/main/java/com/example/myfirstapp/Song.kt
  UMC_6th/app/src/main/java/com/example/myfirstapp/SongActivity.kt
  UMC_6th/app/src/main/java/com/example/myfirstapp/SongDao.kt
  UMC_6th/app/src/main/java/com/example/myfirstapp/SongDatabase.kt
  UMC_6th/app/src/main/res/drawable/custom_snackbar_bg.xml
  UMC_6th/app/src/main/res/layout/activity_main.xml
  UMC_6th/app/src/main/res/layout/activity_song.xml
  UMC_6th/app/src/main/res/layout/custom_snackbar.xml
  UMC_6th/app/src/main/res/layout/item_album.xml
  UMC_6th/app/src/main/res/raw/music_bboom.mp3
  UMC_6th/app/src/main/res/raw/music_boy.mp3
  UMC_6th/app/src/main/res/raw/music_butter.mp3
  UMC_6th/app/src/main/res/raw/music_flu.mp3
  UMC_6th/app/src/main/res/raw/music_next.mp3
Labels: Ch7

#34 [Maro/#33] feat :: 7주차 구현
  .idea/workspace.xml
  UMC_6th/app/build.gradle.kts
  UMC_6th/app/src/main/java/com/example/umc_6th/Album.kt
  UMC_6th/app/src/main/java/com/example/umc_6th/AlbumDao.kt
  UMC_6th/app/src/main/java/com/example/umc_6th/AlbumFragment.kt
  UMC_6th/app/src/main/java/com/example/umc_6th/AlbumRVAdapter.kt
  UMC_6th/app/src/main/java/com/example/umc_6th/AlbumVPAdapter.kt
  UMC_6th/app/src/main/java/com/example/umc_6th/BottomSheetFragment.kt
  UMC_6th/app/src/main/java/com/example/umc_6th/CommunicationInterface.kt
  UMC_6th/app/src/main/java/com/example/umc_6th/Constant.kt
  UMC_6th/app/src/main/java/com/example/umc_6th/CustomSnackbar.kt
  UMC_6th/app/src/main/java/com/example/umc_6th/DetailFragment.kt
  UMC_6th/app/src/main/java/com/example/umc_6th/ForegroundService.kt
  UMC_6th/app/src/main/java/com/example/umc_6th/HomeFragment.kt
  UMC_6th/app/src/main/java/com/example/umc_6th/LockerAlbumRVAdapter.kt
  UMC_6th/app/src/main/java/com/example/umc_6th/LockerFragment.kt
  UMC_6th/app/src/main/java/com/example/umc_6th/LockerVPAdapter.kt
  UMC_6th/app/src/main/java/com/example/umc_6th/MainActivity.kt
  UMC_6th/app/src/main/java/com/example/umc_6th/PannelVPAdapter.kt
  UMC_6th/app/src/main/java/com/example/umc_6th/SavedSongFragment.kt
  UMC_6th/app/src/main/java/com/example/umc_6th/Song.kt
  UMC_6th/app/src/main/java/com/example/umc_6th/SongActivity.kt
  UMC_6th/app/src/main/java/com/example/umc_6th/SongDao.kt
  UMC_6th/app/src/main/java/com/example/umc_6th/SongDatabase.kt
  UMC_6th/app/src/main/java/com/example/umc_6th/SongFragment.kt
  UMC_6th/app/src/main/java/com/example/umc_6th/song.kt
  UMC_6th/app/src/main/res/drawable/btn_editbar_delete.png
  UMC_6th/app/src/main/res/drawable/btn_editbar_download.png
  UMC_6th/app/src/main/res/drawable/btn_editbar_mylist.png
  UMC_6th/app/src/main/res/drawable/btn_editbar_play.png
  UMC_6th/app/src/main/res/drawable/custom_snackbar_bg.xml
  UMC_6th/app/src/main/res/layout/custom_snackbar.xml
  UMC_6th/app/src/main/res/layout/fragment_bottom_sheet.xml
  UMC_6th/app/src/main/res/layout/fragment_locker.xml
  UMC_6th/app/src/main/res/layout/item_album.xml
  UMC_6th/app/src/main/res/raw/music_bboom.mp3
  UMC_6th/app/src/main/res/raw/music_boy.mp3
  UMC_6th/app/src/main/res/raw/music_butter.mp3
  UMC_6th/app/src/main/res/raw/music_flu.mp3
  UMC_6th/app/src/main/res/raw/music_next.mp3
  UMC_6th/build.gradle.kts
Labels: Ch7

#37 [Simba/#33] :: feat 7주차 구현
  UMC_6th/.idea/shelf/Uncommitted_changes_before_Checkout_at_5_18_24,_7_44 PM_[Changes]/shelved.patch
  UMC_6th/.idea/shelf/Uncommitted_changes_before_Checkout_at_5_18_24__7_44PM__Changes_.xml
  UMC_6th/app/build.gradle.kts
  UMC_6th/app/src/main/java/com/example/umc_6th/Album.kt
  UMC_6th/app/src/main/java/com/example/umc_6th/AlbumDao.kt
  UMC_6th/app/src/main/java/com/example/umc_6th/AlbumRVAdapter.kt
  UMC_6th/app/src/main/java/com/example/umc_6th/BottomSheetFragment.kt
  UMC_6th/app/src/main/java/com/example/umc_6th/CustomSnackbar.kt
  UMC_6th/app/src/main/java/com/example/umc_6th/HomeFragment.kt
  UMC_6th/app/src/main/java/com/example/umc_6th/LockerAlbumRVAdapter.kt
  UMC_6th/app/src/main/java/com/example/umc_6th/LockerFragment.kt
  UMC_6th/app/src/main/java/com/example/umc_6th/MainActivity.kt
  UMC_6th/app/src/main/java/com/example/umc_6th/SavedSongFragment.kt
  UMC_6th/app/src/main/java/com/example/umc_6th/Song.kt
  UMC_6th/app/src/main/java/com/example/umc_6th/SongActivity.kt
  UMC_6th/app/src/main/java/com/example/umc_6th/SongDao.kt
  UMC_6th/app/src/main/java/com/example/umc_6th/SongDatabase.kt
  UMC_6th/app/src/main/res/drawable/btn_editbar_addplaylist.png
  UMC_6th/app/src/main/res/drawable/btn_editbar_delete.png
  UMC_6th/app/src/main/res/drawable/btn_editbar_download.png
  UMC_6th/app/src/main/res/drawable/btn_editbar_mylist.png
  UMC_6th/app/src/main/res/drawable/btn_editbar_play.png
  UMC_6th/app/src/main/res/drawable/custom_snackbar_bg.xml
  UMC_6th/app/src/main/res/layout/custom_snackbar.xml
  UMC_6th/app/src/main/res/layout/fragment_bottom_sheet.xml
  UMC_6th/app/src/main/res/layout/fragment_home.xml
  UMC_6th/app/src/main/res/layout/item_album.xml
  UMC_6th/app/src/main/res/raw/music_bboom.mp3
  UMC_6th/app/src/main/res/raw/music_boy.mp3
  UMC_6th/app/src/main/res/raw/music_butter.mp3
  UMC_6th/app/src/main/res/raw/music_flu.mp3
  UMC_6th/app/src/main/res/raw/music_next.mp3
Labels: Ch7

#39 [Kara/#38] feat : 8주차 구현 완료
  UMC_6th/app/src/main/AndroidManifest.xml
  UMC_6th/app/src/main/java/com/example/myfirstapp/Album.kt
  UMC_6th/app/src/main/java/com/example/myfirstapp/AlbumDao.kt
  UMC_6th/app/src/main/java/com/example/myfirstapp/AlbumFragment.kt
  UMC_6th/app/src/main/java/com/example/myfirstapp/Like.kt
  UMC_6th/app/src/main/java/com/example/myfirstapp/LockerFragment.kt
  UMC_6th/app/src/main/java/com/example/myfirstapp/LoginActivity.kt
  UMC_6th/app/src/main/java/com/example/myfirstapp/SavedAlbumFragment.kt
  UMC_6th/app/src/main/java/com/example/myfirstapp/SavedAlbumRVAdapter.kt
  UMC_6th/app/src/main/java/com/example/myfirstapp/SignUpActivity.kt
  UMC_6th/app/src/main/java/com/example/myfirstapp/SongDatabase.kt
  UMC_6th/app/src/main/java/com/example/myfirstapp/User.kt
  UMC_6th/app/src/main/java/com/example/myfirstapp/UserDao.kt
  UMC_6th/app/src/main/res/drawable/not_selected_button.xml
  UMC_6th/app/src/main/res/drawable/selected_button.xml
  UMC_6th/app/src/main/res/layout/activity_login.xml
  UMC_6th/app/src/main/res/layout/activity_sign_up.xml
  UMC_6th/app/src/main/res/layout/fragment_locker.xml
  UMC_6th/app/src/main/res/layout/fragment_look.xml
  UMC_6th/app/src/main/res/layout/fragment_savedalbum.xml
  UMC_6th/app/src/main/res/layout/item_album.xml
Labels: Ch8

#42 [Simba/#38] feat :: 8주차 완료
  UMC_6th/app/src/main/AndroidManifest.xml
  UMC_6th/app/src/main/java/com/example/umc_6th/AlbumDao.kt
  UMC_6th/app/src/main/java/com/example/umc_6th/AlbumFragment.kt
  UMC_6th/app/src/main/java/com/example/umc_6th/Like.kt
  UMC_6th/app/src/main/java/com/example/umc_6th/LockerAlbumRVAdapter.kt
  UMC_6th/app/src/main/java/com/example/umc_6th/LockerFragment.kt
  UMC_6th/app/src/main/java/com/example/umc_6th/LoginActivity.kt
  UMC_6th/app/src/main/java/com/example/umc_6th/LookFragment.kt
  UMC_6th/app/src/main/java/com/example/umc_6th/MainActivity.kt
  UMC_6th/app/src/main/java/com/example/umc_6th/SavedAlbumFragment.kt
  UMC_6th/app/src/main/java/com/example/umc_6th/SavedAlbumRVAdapter.kt
  UMC_6th/app/src/main/java/com/example/umc_6th/SignUpActivity.kt
  UMC_6th/app/src/main/java/com/example/umc_6th/SongActivity.kt
  UMC_6th/app/src/main/java/com/example/umc_6th/SongDatabase.kt
  UMC_6th/app/src/main/java/com/example/umc_6th/User.kt
  UMC_6th/app/src/main/java/com/example/umc_6th/UserDao.kt
  UMC_6th/app/src/main/res/drawable/not_selected_button.xml
  UMC_6th/app/src/main/res/drawable/selected_button.xml
  UMC_6th/app/src/main/res/layout/activity_login.xml
  UMC_6th/app/src/main/res/layout/activity_signup.xml
  UMC_6th/app/src/main/res/layout/fragment_locker_savedalbum.xml
  UMC_6th/app/src/main/res/layout/fragment_look.xml
Labels: Ch8

#41 [Maro/#38] Feat :: 8주차 구현 완료
  .idea/workspace.xml
  UMC_6th/app/src/main/AndroidManifest.xml
  UMC_6th/app/src/main/java/com/example/umc_6th/Album.kt
  UMC_6th/app/src/main/java/com/example/umc_6th/AlbumDao.kt
  UMC_6th/app/src/main/java/com/example/umc_6th/AlbumFragment.kt
  UMC_6th/app/src/main/java/com/example/umc_6th/Like.kt
  UMC_6th/app/src/main/java/com/example/umc_6th/LockerFragment.kt
  UMC_6th/app/src/main/java/com/example/umc_6th/LoginActivity.kt
  UMC_6th/app/src/main/java/com/example/umc_6th/LookFragment.kt
  UMC_6th/app/src/main/java/com/example/umc_6th/MainActivity.kt
  UMC_6th/app/src/main/java/com/example/umc_6th/SavedAlbumFragment.kt
  UMC_6th/app/src/main/java/com/example/umc_6th/SavedAlbumRVAdapter.kt
  UMC_6th/app/src/main/java/com/example/umc_6th/SignUpActivity.kt
  UMC_6th/app/src/main/java/com/example/umc_6th/SongDatabase.kt
  UMC_6th/app/src/main/java/com/example/umc_6th/User.kt
  UMC_6th/app/src/main/java/com/example/umc_6th/UserDao.kt
  UMC_6th/app/src/main/res/drawable/btn_editbar_addplaylist.png
  UMC_6th/app/src/main/res/drawable/not_selected_button.xml
  UMC_6th/app/src/main/res/drawable/selected_button.xml
  UMC_6th/app/src/main/res/layout/activity_login.xml
  UMC_6th/app/src/main/res/layout/activity_sign_up.xml
  UMC_6th/app/src/main/res/layout/fragment_bottom_sheet.xml
  UMC_6th/app/src/main/res/layout/fragment_locker.xml
  UMC_6th/app/src/main/res/layout/fragment_look.xml
  UMC_6th/app/src/main/res/layout/fragment_saved_album.xml
Labels: Ch8

#45 [Maro/#43] feat :: 9주차 구현
  .idea/other.xml
  .idea/workspace.xml
  UMC_6th/app/build.gradle.kts
  UMC_6th/app/src/main/AndroidManifest.xml
  UMC_6th/app/src/main/java/com/example/umc_6th/ApiRepository.kt
  UMC_6th/app/src/main/java/com/example/umc_6th/AuthApi.kt
  UMC_6th/app/src/main/java/com/example/umc_6th/AuthService.kt
  UMC_6th/app/src/main/java/com/example/umc_6th/BaseResponse.kt
  UMC_6th/app/src/main/java/com/example/umc_6th/LockerFragment.kt
  UMC_6th/app/src/main/java/com/example/umc_6th/LoginActivity.kt
  UMC_6th/app/src/main/java/com/example/umc_6th/LoginView.kt
  UMC_6th/app/src/main/java/com/example/umc_6th/LookFragment.kt
  UMC_6th/app/src/main/java/com/example/umc_6th/LookView.kt
  UMC_6th/app/src/main/java/com/example/umc_6th/MainActivity.kt
  UMC_6th/app/src/main/java/com/example/umc_6th/RetrofitInstance.kt
  UMC_6th/app/src/main/java/com/example/umc_6th/SignUpActivity.kt
  UMC_6th/app/src/main/java/com/example/umc_6th/SignUpView.kt
  UMC_6th/app/src/main/java/com/example/umc_6th/SongApi.kt
  UMC_6th/app/src/main/java/com/example/umc_6th/SongRVAdapter.kt
  UMC_6th/app/src/main/java/com/example/umc_6th/SongResponnse.kt
  UMC_6th/app/src/main/java/com/example/umc_6th/SongService.kt
  UMC_6th/app/src/main/java/com/example/umc_6th/User.kt
  UMC_6th/app/src/main/res/layout/fragment_look.xml
  UMC_6th/app/src/main/res/layout/item_song.xml
Labels: Ch9

#44 [Nunu/#43] feat: 9구차 구현
  UMC_6th/.idea/deploymentTargetSelector.xml
  UMC_6th/app/build.gradle.kts
  UMC_6th/app/src/main/AndroidManifest.xml
  UMC_6th/app/src/main/java/com/example/umc_6th/AlbumApi.kt
  UMC_6th/app/src/main/java/com/example/umc_6th/AlbumResponse.kt
  UMC_6th/app/src/main/java/com/example/umc_6th/AlbumService.kt
  UMC_6th/app/src/main/java/com/example/umc_6th/ApiRepository.kt
  UMC_6th/app/src/main/java/com/example/umc_6th/AuthApi.kt
  UMC_6th/app/src/main/java/com/example/umc_6th/AuthService.kt
  UMC_6th/app/src/main/java/com/example/umc_6th/BaseResponse.kt
  UMC_6th/app/src/main/java/com/example/umc_6th/HomeAlbumView.kt
  UMC_6th/app/src/main/java/com/example/umc_6th/HomeFragment.kt
  UMC_6th/app/src/main/java/com/example/umc_6th/LockerFragment.kt
  UMC_6th/app/src/main/java/com/example/umc_6th/LoginActivity.kt
  UMC_6th/app/src/main/java/com/example/umc_6th/LoginView.kt
  UMC_6th/app/src/main/java/com/example/umc_6th/LookFragment.kt
  UMC_6th/app/src/main/java/com/example/umc_6th/LookView.kt
  UMC_6th/app/src/main/java/com/example/umc_6th/MainActivity.kt
  UMC_6th/app/src/main/java/com/example/umc_6th/RetrofitInstance.kt
  UMC_6th/app/src/main/java/com/example/umc_6th/SignUpActivity.kt
  UMC_6th/app/src/main/java/com/example/umc_6th/SignUpView.kt
  UMC_6th/app/src/main/java/com/example/umc_6th/SongApi.kt
  UMC_6th/app/src/main/java/com/example/umc_6th/SongResponse.kt
  UMC_6th/app/src/main/java/com/example/umc_6th/SongService.kt
  UMC_6th/app/src/main/java/com/example/umc_6th/SplashActivity.kt
  UMC_6th/app/src/main/java/com/example/umc_6th/adapter/SongRecyclerViewAdapter.kt
  UMC_6th/app/src/main/res/layout/fragment_look.xml
  UMC_6th/app/src/main/res/layout/item_song.xml
Labels: Ch9
